"""ES-38 — confirmed Customer Framework Report Word export."""

from __future__ import annotations

from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.shared import Inches, Pt, RGBColor

from services.framework.customer_view import resolve_customer_view
from services.framework.eligibility import RenderBlocked


def render_customer_docx(framework: dict[str, Any], *, lang: str = "en") -> bytes:
    """Render a professional .docx for a confirmed (or draft) customer framework."""
    view = resolve_customer_view(framework, lang=lang)
    render = framework.get("render") or {}
    if not render.get("allowed"):
        readiness = int((framework.get("quality_scores") or {}).get("build_readiness") or 0)
        raise RenderBlocked(
            render.get("reason") or "Customer report is not ready for export.",
            readiness,
        )

    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)

    title = document.add_heading(str(view.get("title") or framework.get("title") or "Customer Framework Report"), 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
    for run in title.runs:
        run.font.color.rgb = RGBColor(14, 28, 54)

    cover = view.get("cover") or framework.get("cover") or {}
    meta_lines = [
        ("Department", str(view.get("department") or framework.get("department") or "")),
        ("Opportunity", str(view.get("opportunity_id") or framework.get("opportunity_id") or "")),
        ("Status", str(cover.get("status_label") or framework.get("status") or "")),
    ]
    scores = view.get("quality_scores") or framework.get("quality_scores") or {}
    if scores:
        meta_lines.append(("Build-readiness", f"{scores.get('build_readiness', '')}/100"))

    for label, value in meta_lines:
        if not value:
            continue
        paragraph = document.add_paragraph()
        label_run = paragraph.add_run(f"{label}: ")
        label_run.bold = True
        paragraph.add_run(value)

    review_summary = framework.get("review_summary") or {}
    management_summary = review_summary.get("management_summary") or _chapter_text(view, "1")
    if management_summary:
        document.add_heading("Management summary", level=1)
        document.add_paragraph(management_summary)

    for chapter in view.get("chapters") or []:
        chapter_id = str(chapter.get("chapter_id") or "")
        chapter_title = str(chapter.get("title") or "")
        document.add_heading(f"{chapter_id} {chapter_title}".strip(), level=1)
        _append_chapter_body(document, chapter.get("body"))

    footer = document.sections[0].footer.paragraphs[0]
    footer.text = (
        f"{framework.get('opportunity_id')} · v{framework.get('version', 1)} · "
        "Generated by the Borek AI Suite Framework Engine."
    )
    footer.runs[0].font.size = Pt(8)

    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _append_chapter_body(document: Document, body: Any) -> None:
    if isinstance(body, str):
        if body.strip():
            document.add_paragraph(body.strip())
        return
    if not isinstance(body, list):
        return
    for block in body:
        if not isinstance(block, dict):
            continue
        block_type = str(block.get("block") or "")
        if block_type == "prose" and block.get("text"):
            document.add_paragraph(str(block["text"]))
        elif block_type == "bullets":
            for item in block.get("items") or []:
                document.add_paragraph(str(item), style="List Bullet")
        elif block.get("summary"):
            document.add_paragraph(str(block["summary"]))
        elif block.get("text"):
            document.add_paragraph(str(block["text"]))
        else:
            lines = [f"{key}: {value}" for key, value in block.items() if key != "block" and value]
            if lines:
                document.add_paragraph("; ".join(lines))


def _chapter_text(view: dict[str, Any], chapter_id: str) -> str:
    for chapter in view.get("chapters") or []:
        if str(chapter.get("chapter_id")) == chapter_id:
            body = chapter.get("body")
            if isinstance(body, str):
                return body.strip()
    return ""
